/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifrn.pds.projeto.ui;

import br.edu.ifrn.pds.Filme;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author 20201114010010
 */
public class CadastroFilme extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFilme
     */
    public CadastroFilme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jtfDuracao = new javax.swing.JTextField();
        jtfAno = new javax.swing.JTextField();
        jtfAvaliacao = new javax.swing.JTextField();
        jbtnSalvar = new javax.swing.JButton();
        jbtnRemover = new javax.swing.JButton();
        jbtnAtualizar = new javax.swing.JButton();
        jbtnListar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaFilmes = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Título:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Duração:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ano:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Avaliação:");

        jbtnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnSalvar.setText("Salvar");
        jbtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarActionPerformed(evt);
            }
        });

        jbtnRemover.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnRemover.setText("Remover (id)");
        jbtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoverActionPerformed(evt);
            }
        });

        jbtnAtualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnAtualizar.setText("Atualizar (id)");
        jbtnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAtualizarActionPerformed(evt);
            }
        });

        jbtnListar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnListar.setText("Listar");
        jbtnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListarActionPerformed(evt);
            }
        });

        jtaFilmes.setColumns(20);
        jtaFilmes.setRows(5);
        jScrollPane1.setViewportView(jtaFilmes);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel5.setText("Registrador de filmes");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Id:");

        jbtnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnBuscar.setText("Buscar (título)");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfDuracao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(jtfAno, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfAvaliacao, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtfId)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbtnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(jbtnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbtnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnBuscar)
                        .addGap(92, 92, 92)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtfDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtfAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnSalvar)
                            .addComponent(jbtnRemover))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnAtualizar)
                            .addComponent(jbtnListar))
                        .addGap(18, 18, 18)
                        .addComponent(jbtnBuscar))
                    .addComponent(jScrollPane1))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarActionPerformed

        String titulo = jtfTitulo.getText();
        int duracao = Integer.parseInt(jtfDuracao.getText());
        int ano = Integer.parseInt(jtfAno.getText());
        double avaliacao = Double.parseDouble(jtfAvaliacao.getText());

        Filme objFilme = new Filme ();
        objFilme.setTitulo(titulo);
        objFilme.setDuracao(duracao);
        objFilme.setAno(ano);
        objFilme.setAvaliacao(avaliacao);
        
        boolean resultado = false;
        if (verificarExistencia(titulo) == false) {
           resultado = inserirFilme(objFilme); 
        }

        if (resultado) {
            JOptionPane.showMessageDialog(rootPane, "Filme cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "O filme não pôde ser cadastrado.");
        }

    }//GEN-LAST:event_jbtnSalvarActionPerformed

    private void jbtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoverActionPerformed

        int id = Integer.parseInt(jtfId.getText());
        
        Filme filme = buscarFilmeId(id);
        
        if (filme != null) {
            boolean resultado = removerFilme(id);
            
            if (resultado) {
                JOptionPane.showMessageDialog(rootPane, "Filme removido com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "O filme não pôde ser removido.");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Esse filme não existe.");
        }

    }//GEN-LAST:event_jbtnRemoverActionPerformed

    private void jbtnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAtualizarActionPerformed

        int id = Integer.parseInt(jtfId.getText());
        
        Filme filme = buscarFilmeId(id);

        if(filme != null){
            filme.setTitulo(jtfTitulo.getText());
            filme.setDuracao(Integer.parseInt(jtfDuracao.getText()));
            filme.setAno(Integer.parseInt(jtfAno.getText()));
            filme.setAvaliacao(Double.parseDouble(jtfAvaliacao.getText()));

            boolean resultado = alterarFilme(filme);

            if (resultado) {
                JOptionPane.showMessageDialog(rootPane, "Filme atualizado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "O filme não pôde ser atualizado.");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Esse filme não existe.");
        }

    }//GEN-LAST:event_jbtnAtualizarActionPerformed

    private void jbtnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListarActionPerformed

        List<Filme> filmes = buscarTodos();

        jtaFilmes.setText("");

        for (Filme filme : filmes) {
            jtaFilmes.append(filme.toString());
            jtaFilmes.append("\n");
        }

    }//GEN-LAST:event_jbtnListarActionPerformed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        
        String titulo = jtfTitulo.getText();
        
        Filme filme = buscarFilme(titulo);
        
        if (filme != null) {
            jtfId.setText(Integer.toString(filme.getId()));
            jtfDuracao.setText(Integer.toString(filme.getDuracao()));
            jtfAno.setText(Integer.toString(filme.getAno()));
            jtfAvaliacao.setText(Double.toString(filme.getAvaliacao()));
        } else {
            JOptionPane.showMessageDialog(rootPane, "Esse filme não existe.");
        }
        
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFilme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAtualizar;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnListar;
    private javax.swing.JButton jbtnRemover;
    private javax.swing.JButton jbtnSalvar;
    private javax.swing.JTextArea jtaFilmes;
    private javax.swing.JTextField jtfAno;
    private javax.swing.JTextField jtfAvaliacao;
    private javax.swing.JTextField jtfDuracao;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfTitulo;
    // End of variables declaration//GEN-END:variables

    private static boolean inserirFilme(br.edu.ifrn.pds.Filme filme) {
        br.edu.ifrn.pds.FilmeWS_Service service = new br.edu.ifrn.pds.FilmeWS_Service();
        br.edu.ifrn.pds.FilmeWS port = service.getFilmeWSPort();
        return port.inserirFilme(filme);
    }

    private static boolean verificarExistencia(java.lang.String titulo) {
        br.edu.ifrn.pds.FilmeWS_Service service = new br.edu.ifrn.pds.FilmeWS_Service();
        br.edu.ifrn.pds.FilmeWS port = service.getFilmeWSPort();
        return port.verificarExistencia(titulo);
    }

    private static boolean removerFilme(int id) {
        br.edu.ifrn.pds.FilmeWS_Service service = new br.edu.ifrn.pds.FilmeWS_Service();
        br.edu.ifrn.pds.FilmeWS port = service.getFilmeWSPort();
        return port.removerFilme(id);
    }

    private static Filme buscarFilmeId(int id) {
        br.edu.ifrn.pds.FilmeWS_Service service = new br.edu.ifrn.pds.FilmeWS_Service();
        br.edu.ifrn.pds.FilmeWS port = service.getFilmeWSPort();
        return port.buscarFilmeId(id);
    }

    private static boolean alterarFilme(br.edu.ifrn.pds.Filme filme) {
        br.edu.ifrn.pds.FilmeWS_Service service = new br.edu.ifrn.pds.FilmeWS_Service();
        br.edu.ifrn.pds.FilmeWS port = service.getFilmeWSPort();
        return port.alterarFilme(filme);
    }

    private static java.util.List<br.edu.ifrn.pds.Filme> buscarTodos() {
        br.edu.ifrn.pds.FilmeWS_Service service = new br.edu.ifrn.pds.FilmeWS_Service();
        br.edu.ifrn.pds.FilmeWS port = service.getFilmeWSPort();
        return port.buscarTodos();
    }

    private static Filme buscarFilme(java.lang.String titulo) {
        br.edu.ifrn.pds.FilmeWS_Service service = new br.edu.ifrn.pds.FilmeWS_Service();
        br.edu.ifrn.pds.FilmeWS port = service.getFilmeWSPort();
        return port.buscarFilme(titulo);
    }

    private static Filme buscarFilmeId_1(int id) {
        br.edu.ifrn.pds.FilmeWS_Service service = new br.edu.ifrn.pds.FilmeWS_Service();
        br.edu.ifrn.pds.FilmeWS port = service.getFilmeWSPort();
        return port.buscarFilmeId(id);
    }
}
